#!/usr/bin/env python3
"""Regenerate Binance Spot SBE codecs from an official XML schema."""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import tempfile
import urllib.request
from pathlib import Path


SBE_VERSION = "1.37.1"
SBE_JAR_SHA256 = "20eb13929249092a01fdcd1e8351a55af80bab5414a9fda19d0eddf6f5983a66"
SBE_JAR_URL = (
    "https://repo1.maven.org/maven2/uk/co/real-logic/"
    f"sbe-all/{SBE_VERSION}/sbe-all-{SBE_VERSION}.jar"
)
BINANCE_SCHEMA_COMMIT = "6b8372cad7cecbdf5dd88a3372eafff51988c5cf"
BINANCE_SCHEMA_SHA256 = "542776a038883dafe962341a041323ff5d8d3e36f1b860ab60156a88a4080bcf"
SCHEMA_URL = (
    "https://raw.githubusercontent.com/binance/binance-spot-api-docs/"
    f"{BINANCE_SCHEMA_COMMIT}/sbe/schemas/spot_3_5.xml"
)

MODULE_HEADER = """//! Generated SBE codecs for Binance Spot API (schema 3:5).
//!
//! This code is auto-generated by Real Logic's SBE generator from Binance's
//! official XML schema. Do not edit manually.

#![forbid(unsafe_code)]
#![allow(clippy::all)]
#![expect(clippy::missing_errors_doc)]
#![expect(clippy::missing_panics_doc)]
#![expect(clippy::return_self_not_must_use)]
#![expect(clippy::semicolon_if_nothing_returned)]
#![expect(clippy::use_self)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(ambiguous_glob_reexports)]
#![allow(unused_imports)]
#![allow(dead_code)]

use ::core::convert::TryInto;

"""

SCHEMA_EXPORTS = """pub use crate::SBE_SCHEMA_ID;
pub use crate::SBE_SCHEMA_VERSION;
pub use crate::SBE_SEMANTIC_VERSION;"""
LOCAL_SCHEMA_EXPORTS = (
    "use super::*;\n"
    "pub use super::{SBE_SCHEMA_ID, SBE_SCHEMA_VERSION, SBE_SEMANTIC_VERSION};"
)


def download(url: str, destination: Path) -> None:
    request = urllib.request.Request(url, headers={"User-Agent": "StratNeo SBE generator"})
    with urllib.request.urlopen(request) as response:
        destination.write_bytes(response.read())


def verify_sha256(path: Path, expected: str, label: str) -> None:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != expected:
        raise SystemExit(
            f"{label} SHA-256 mismatch: expected {expected}, received {digest}"
        )


def transform_codec(source: Path, destination: Path) -> None:
    text = source.read_text()
    if SCHEMA_EXPORTS in text and text.startswith("use crate::*;\n\n"):
        text = text.removeprefix("use crate::*;\n\n")
    text = text.replace(SCHEMA_EXPORTS, LOCAL_SCHEMA_EXPORTS)
    text = text.replace("crate::", "super::")
    text = "\n".join(line.rstrip() for line in text.splitlines()) + "\n"
    destination.write_text(text)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--java", default=os.environ.get("JAVA") or shutil.which("java"))
    parser.add_argument("--jar", type=Path)
    parser.add_argument("--schema", type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("crates/adapters/binance/src/spot/sbe/generated"),
    )
    parser.add_argument("--rustfmt", default=os.environ.get("RUSTFMT") or shutil.which("rustfmt"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.java:
        raise SystemExit("Java was not found; pass --java or set JAVA")
    if not args.rustfmt:
        raise SystemExit("rustfmt was not found; pass --rustfmt or set RUSTFMT")

    output = args.output.resolve()
    expected_suffix = Path("crates/adapters/binance/src/spot/sbe/generated")
    if not output.as_posix().endswith(expected_suffix.as_posix()):
        raise SystemExit(f"refusing to replace unexpected output directory: {output}")

    with tempfile.TemporaryDirectory(prefix="binance-spot-sbe-") as temp_name:
        temp = Path(temp_name)
        jar = args.jar or temp / f"sbe-all-{SBE_VERSION}.jar"
        schema = args.schema or temp / "spot_3_5.xml"
        if args.jar is None:
            download(SBE_JAR_URL, jar)
        if args.schema is None:
            download(SCHEMA_URL, schema)
        verify_sha256(jar, SBE_JAR_SHA256, "SBE generator jar")
        verify_sha256(schema, BINANCE_SCHEMA_SHA256, "Binance Spot schema")

        generated_root = temp / "generated"
        subprocess.run(
            [
                args.java,
                "--add-opens",
                "java.base/jdk.internal.misc=ALL-UNNAMED",
                "-Dsbe.target.language=Rust",
                f"-Dsbe.output.dir={generated_root}",
                "-Dsbe.errorLog=yes",
                "-jar",
                str(jar),
                str(schema),
            ],
            check=True,
        )

        source = generated_root / "spot_sbe" / "src"
        staged = temp / "staged"
        staged.mkdir()
        for source_file in sorted(source.glob("*.rs")):
            if source_file.name == "lib.rs":
                raw = source_file.read_text()
                modules = raw.index("pub mod ")
                (staged / "mod.rs").write_text(MODULE_HEADER + raw[modules:])
            else:
                transform_codec(source_file, staged / source_file.name)

        if output.exists():
            shutil.rmtree(output)
        shutil.copytree(staged, output)
        subprocess.run([args.rustfmt, "--edition", "2024", str(output / "mod.rs")], check=True)


if __name__ == "__main__":
    main()
